### ISSUE TITLE
Does not effect menu color

### ISSUE THREAD

**Issue by praneethmendu** [p-e-w/GTKDarkThemeVariantSetter#9]
I do not know if it was never intended to but the menu color is still which is the biggest problem for me. Please let me know if this problem is unique to me I will provide more details.

If not I hope someone can suggest a workaround.

**Comment by p-e-w** [comment]
That's because Sublime uses GTK+ 2, which doesn't support theme variants at all. The window manager has nothing to do with either GTK+ 2 or 3, so GTK+ 3 sets the `GTK_THEME_VARIANT` window property to `dark` when a dark theme is used to instruct the window manager to draw dark decorations. The same can be done for GTK+ 2 windows, which is exactly what this package does.

The menu, however, is part of the client area and subject to the GTK+ theme. GTK+ 2 themes don't have light/dark variants, so you have a choice to either hide the menu bar or use a GTK+ 2 theme that is dark by default.

**Comment by praneethmendu** [comment]
Thanks man 👍
